### PR TITLE
fix: sync function update

### LINKED ISSUE #15: [sync function update] Sync data to smart contract
Have a look at https://github.com/State-Channel-4/backend/blob/main/controllers/contract.js#L17 and update the function with new smart contract. The function needs update related to sending data to smart contract in correct format. 

1. Check the contract at : https://github.com/State-Channel-4/contracts
2. mongodb schema : https://github.com/State-Channel-4/backend/blob/main/models/schema.js

### PR DESCRIPTION
**Pull request by jp4g**
Should be good to go- changes:
  - adds a `./docker/docker-compose.yml` script that provides anvil local RPC and mongodb
    - run `yarn docker up` or `yarn docker up -d` (shut down with `yarn docker down`) to use
    - run `yarn docker:clean` to remove artifacts from containers
  - adds `./docker/populate.js` script which drives user enrollment & tag/ url submission through the api
    - run `yarn populate` to use
  - set .example.env private key to anvil test private key to provide gas
  - remove syncing of User
    - remove `syncedToBlockchain` field from User schema
  - Update tags, urls to sync with current contract
    - Filters Tag/ URL documents from db to only commit tags/ urls that are not synced
    - Marks `syncedWithBlockchain` as true in Tag/ URL documents once synced
  - `syncDataToSmartContract` now returns response through express and does not timeout on http

### CODE REVIEW

**Comment by jp4g** [comment]
uses https://github.com/State-Channel-4/contracts/pull/5

**Review by NicoSerranoP — APPROVED** [review]

File: controllers/urls.js [hunk 1]
```diff
@@ -88,44 +89,39 @@ const getMixedURLs = async (req, res) => {
...
-
-    await existingUser.save();
-    return res.json(existingUser);
-  } catch (err) {
-    console.error(err);
-    return res.status(500).json({ error: "We couldn't update the likes" });
-  }
-};
+const getContentToSync = async () => {
+  return await await Url.find({ syncedToBlockchain: false })
```
Comment (hackertron) [inline controllers/urls.js]: There are 2 await keywords here, typo or needed ?
